name: MacOS

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    
    steps:
      - uses: actions/checkout@v3
      
	  - uses: maxim-lobanov/setup-xcode@v1
		with:
		  xcode-version: '16.1'

      - name: download dependency
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ./downloadDep.sh
        shell: sh

      - name: Generate Project
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ./bootstrap.sh -UniversalBinary
        shell: sh

      - name: Build solution
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          xcodebuild build -workspace ShaderHelper.xcworkspace -scheme ShaderHelper -configuration Shipping -sdk macosx
          xcodebuild build -workspace ShaderHelper.xcworkspace -scheme UnitTestUtil -configuration Shipping -sdk macosx
          xcodebuild build -workspace ShaderHelper.xcworkspace -scheme UnitTestGpuApi -configuration Shipping -sdk macosx
        
#       - name: Upload
#         uses: actions/upload-artifact@v3
#         with:
#           name: ShaderHelper-artifact(${{ matrix.os }})
#           path: |
#             Binaries/Mac/
#             Resource/
#             !Binaries/Mac/*.dSYM
#             External/UE/Shader/OpenGL/
