name: Windows

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2019]
        
    name: ${{ matrix.os == 'windows-latest' && 'Windows(vs2022)' || matrix.os == 'windows-2019' && 'Windows(vs2019)' }}
        
    steps:
      - uses: actions/checkout@v3

      - name: Setup Premake
        uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta1"

      - name: Generate Project
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: bootstrap.bat
        shell: cmd

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build solution
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=Debug ShaderHelper.sln
        
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ShaderHelper-artifact(${{ matrix.os }})
          path: |
            Binaries/Win64/
            Resource/
            !Binaries/Win64/*.pdb
            External/UE/Shader/D3D/
